require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.1.9

# Allow longer lines
Metrics/LineLength:
  Max: 200

# rspec uses long describe blocks, so allow long blocks under spec/
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# Allow longer specs
RSpec/ExampleLength:
  Max: 50
