# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.

# TODO: Original rubocop 0.49.1 to do items
# -----------------------------------------------------------------------------
RSpec/FilePath:
  Exclude:
    - 'spec/unit/pdk/validate/metadata/metadata_json_lint_spec.rb'
    - 'spec/unit/pdk/validate/metadata/metadata_syntax_spec.rb'
    - 'spec/unit/pdk/validate/puppet/puppet_lint_spec.rb'
    - 'spec/unit/pdk/validate/puppet/puppet_syntax_spec.rb'
    - 'spec/unit/pdk/validate/ruby/rubocop_spec.rb'

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Exclude:
    - 'spec/acceptance/bundle_management_spec.rb'
    - 'spec/unit/generate/puppet_object_spec.rb'
    - 'spec/unit/template_file_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

# TODO: new rubocop 0.57.2 to do items
# -----------------------------------------------------------------------------
Layout/ClosingHeredocIndentation:
  Description: Checks the indentation of here document closings.
  Enabled: false

Lint/NumberConversion:
  Description: Checks unsafe usage of number conversion methods.
  Enabled: false

Naming/HeredocDelimiterNaming:
  Description: Use descriptive heredoc delimiters.
  StyleGuide: "#heredoc-delimiters"
  Enabled: false
  Blacklist:
  - !ruby/regexp /(^|\s)(EO[A-Z]{1}|END)(\s|$)/

Naming/MemoizedInstanceVariableName:
  Description: Memoized method name should match memo instance variable name.
  Enabled: false

# Supports --auto-correct
# TODO: for our specific failures perhaps #min_by is more appropriate
Performance/UnneededSort:
  Description: Use `min` instead of `sort.first`, `max_by` instead of `sort_by...last`,
    etc.
  Enabled: false

# TODO: decide on specific enforcement
Style/AccessModifierDeclarations:
  Description: Checks style of how access modifiers are used.
  Enabled: false
  EnforcedStyle: group
  SupportedStyles:
  - inline
  - group

# Supports --auto-correct
Style/RescueStandardError:
  Description: Avoid rescuing without specifying an error class.
  Enabled: false
  EnforcedStyle: explicit
  SupportedStyles:
  - implicit
  - explicit

# Supports --auto-correct
Style/StderrPuts:
  Description: Use `warn` instead of `$stderr.puts`.
  StyleGuide: "#warn"
  Enabled: false

# TODO: New rubocop-rspec cops
# -----------------------------------------------------------------------------
RSpec/ContextWording:
  # 313 failures
  Enabled: false

RSpec/SharedExamples:
  # 46 failures
  Enabled: false

RSpec/ExpectInHook:
  # 29 failures
  Enabled: false

RSpec/PredicateMatcher:
  # 19 failures
  Enabled: false

RSpec/MultipleSubjects:
  # 8 failures
  Enabled: false
