source ENV.fetch('GEM_SOURCE', nil) || 'https://rubygems.org'

gem 'beaker', '~> 4.39'
gem 'beaker-abs', '~> 0.11.0'
gem 'beaker-docker', '~> 2'
gem 'beaker-hostgenerator', '~> 2.11.0'
gem 'beaker-puppet', '= 1.29.0'
gem 'beaker-rspec', '= 7.1.0'
gem 'beaker-vmpooler', '= 1.4.0'
gem 'nokogiri', '~> 1.13.6'
gem 'rake'

# net-ping has a implicit dependency on win32-security
gem 'win32-security', require: false if File::ALT_SEPARATOR

group :development do
  gem 'pry'
  gem 'pry-stack_explorer'
end
