source ENV['GEM_SOURCE'] || 'https://rubygems.org'

def location_for(place, fake_version = nil)
  if place =~ %r{^(git:[^#]*)#(.*)}
    [fake_version, { git: Regexp.last_match(1), branch: Regexp.last_match(2), require: false }].compact
  elsif place =~ %r{^file:\/\/(.*)}
    ['>= 0', { path: File.expand_path(Regexp.last_match(1)), require: false }]
  else
    [place, { require: false }]
  end
end

gem 'beaker', *location_for(ENV['BEAKER_VERSION'] || '= 4.10.0')
gem 'beaker-abs', *location_for(ENV['BEAKER_ABS_VERSION'] || '= 0.5.0')
gem 'beaker-hostgenerator', *location_for(ENV['BEAKER_HOSTGENERATOR_VERSION'] || '= 1.1.31')
gem 'beaker-puppet', '= 1.18.5'
gem 'beaker-rspec', '= 6.2.4'
gem 'beaker-vmpooler', '= 1.3.3'
gem 'nokogiri', '= 1.10.4'
gem 'rake', '= 12.3.2'

group :development do
  gem 'pry-byebug', '~> 3.4'
end
