name: "mend"

on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  mend:
    uses: "puppetlabs/cat-github-actions/.github/workflows/tooling_mend_ruby.yml@main"
    secrets: "inherit"
  
  mend_package:
    runs-on: ubuntu-latest
    steps:
      - name: Activate twingate to obtain unreleased build
        uses: twingate/github-action@main
        with:
          service-key: ${{ secrets.TWINGATE_PUBLIC_REPO_KEY }}

      # Apt builds found here: https://artifactory.delivery.puppetlabs.net/ui/native/internal_nightly__local/apt/pool/noble/puppet-nightly/p/pdk
      # curl -X POST "https://artifactory.delivery.puppetlabs.net/artifactory/api/search/aql" -H "Content-Type: text/plain" --data 'items.find({"repo": "internal_nightly__local", "path": {"$match": "apt/pool/jammy/puppet-nightly/p/pdk/*"}}).sort({"$desc": ["created"]}).limit(1)'
      - name: Get latest build name
        id: latest
        run: |
          echo "::set-output name=ver::$(curl -X POST "https://artifactory.delivery.puppetlabs.net/artifactory/api/search/aql" -H "Content-Type: text/plain" --data 'items.find({"repo": "internal_nightly__local", "path": {"$match": "apt/pool/jammy/puppet-nightly/p/pdk/*"}}).sort({"$desc": ["created"]}).limit(1)')"          

      # - name: Install PDK
      #   run: |
      #     wget https://apt.puppetlabs.com/puppet8-release-jammy.deb;
      #     sudo dpkg -i puppet8-release-jammy.deb;
      #     sudo apt-get update -y;
      #     sudo apt-get install pdk -y;
      #     pdk --version;

      # - uses: "ruby/setup-ruby@v1"
      #   with:
      #     ruby-version: 2.7

      # - uses: "actions/setup-java@v4"
      #   with:
      #     distribution: "temurin"
      #     java-version: "17"
  
      # - name: Download unified agent
      #   run: |
      #     curl -o wss-unified-agent.jar https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar;

      # - name: Run Scan
      #   run: |
      #     sudo -E java -jar wss-unified-agent.jar -d /opt/puppetlabs/pdk
      #   env:
      #     WS_APIKEY: ${{ secrets.MEND_API_KEY }}
      #     WS_WSS_URL: https://saas-eu.whitesourcesoftware.com/agent
      #     WS_USERKEY: ${{ secrets.MEND_TOKEN }}
      #     WS_PRODUCTNAME: "DevX"
      #     WS_PROJECTNAME: "${{  github.event.repository.name }}-package"
